Repository TheUpperPart/leaguehub-backend, pull requests merged in 2023-09, with the labels that each got.

#239 Fix#238: 쿼리문 수정 및 메서드 추가
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
Labels: bug

#241 Fix#240: 중괄호 누락 문제 수정 및 불 필요한 필드명 삭제
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: bug

#236 feat#231: 매치 플레이어일 때 현재 진행중인 라운드 표시
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#237 Feat#232: 대회 플레이어의 탈락, 실격 구현
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: feature

#243 Feat#215 : 매치 준비 화면 조회
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerScoreInfo.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchScoreInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#242 Feat#226 유저 준비 상태 완료
  src/main/java/leaguehub/leaguehubbackend/config/StompHandler.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchSetReadyMessage.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchSetStatusMessage.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/exception/MatchPlayerNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
Labels: feature

#251 Refactor#244: 대진표 요청 시 필요한 값 수정
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerInfo.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: refactor

#252 Fix#248: 관리자 여러 명일 때 반환되는 값 수정
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: bug

#253 Refactor#247: 채널 참가하였을 때 반환되는 값 수정
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor

#250 Test#246 : 매치 서비스테스트를 구현
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/test/java/leaguehub/leaguehubbackend/fixture/MatchScoreListFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceScoreTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceTest.java
Labels: test

#263 Feat#261 : Stomp SendTo 통일화
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/resources/application.properties
Labels: feature

#254 Feat#202: 해당 채널의 라운드 당 경기 횟수 개별 설정 기능 구현
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#258 Fix#257 : BadRequest 시 Unauthorized 전달 버그 수정
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPoint.java
Labels: bug

#260 config#259: cors 및 로컬 운영 프로퍼티 분리
  src/main/java/leaguehub/leaguehubbackend/config/CorsConfig.java
  src/main/resources/application-local.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: documentation

#267 Fix#266 : simpMessagingTemplate 사용으로인한 @SendTo 삭제
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
Labels: refactor

#269 Feat#268: 점수 업데이트시 체크 로직 추가
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/resources/application-prod.properties
Labels: enhancement

#265 Feat#264 : 이메일 인증토큰 폼 변경
  src/main/java/leaguehub/leaguehubbackend/service/email/EmailService.java
  src/main/resources/static/emailTemplate.html
  src/test/java/leaguehub/leaguehubbackend/service/email/EmailServiceTest.java
Labels: feature, refactor

#270 fix#245: 반환값 제거, id 체크 로직 누락 추가
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
Labels: bug

#277 Feat#271: 매치 세트 관련 기능 추가
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: enhancement

#274 Refactor : JwtFilter 예외 처리 수정에 따른 테스트 코드 업데이트
  src/test/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPointTest.java
Labels: bug, test

#280 Feat#272: 몽고 DB 추가 및 경기 결과 관련 기능 추가
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/LeaguehubBackendApplication.java
  src/main/java/leaguehub/leaguehubbackend/config/MongoDataConfig.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/GameResult.java
  src/main/java/leaguehub/leaguehubbackend/mongo_repository/GameResultRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/resources/application-local.properties
Labels: documentation, enhancement

#276 Fix#275: 테스트 관련 코드 수정
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: bug

#293 Feat#291 : 매치 상태 조회시 Playerstatus 상태 추가
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerScoreInfo.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#294 Refactor#292 : 체크인 로직 변경
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
Labels: refactor

#285 Feat#282: 매치 세트 설정시 현재 설정한 세트를 불러오는 기능 추가
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#286 Feat#278: 참가자 배정시 이전 매치 상태가 전부 끝났는지 확인하는 로직 추가
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/exception/MatchNotEndException.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#299 FIx#298 : 체크인 에러 수정
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchSetReadyMessage.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
Labels: bug

#289 Config#288 : Redis 설정
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/config/RedisConfig.java
Labels: feature

#302 fix#301: @DestinationVariable 오류 해결
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
Labels: bug

#303 Feat#290 : 채팅 기능 구현
  src/main/java/leaguehub/leaguehubbackend/config/RedisConfig.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchChatController.java
  src/main/java/leaguehub/leaguehubbackend/dto/chat/MatchMessage.java
  src/main/java/leaguehub/leaguehubbackend/exception/chat/ChatExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/chat/ChatExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/chat/exception/MatchChatMessageConversionException.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatService.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatSubscriber.java
Labels: feature

#287 Feat#281: 매치 플레이어 컬럼 추가 및 경기 종료시 추가 로직 구현
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerInfo.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayerResultStatus.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/PlayerStatus.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchSetRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: enhancement

#305 Feat#283: 매치 세트를 생성하는 기능 구현
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchSet.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/exception/ChannelStatusAlreadyException.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchSetRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#308 Refactor#306 : MatchMessage Enum 추가, 타입 변경
  src/main/java/leaguehub/leaguehubbackend/dto/chat/MatchMessage.java
  src/main/java/leaguehub/leaguehubbackend/entity/chat/MessageType.java
Labels: refactor

#309 Feat#307 : 리그(채널) 종료시 채팅 삭제
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatService.java
Labels: feature

#311 Refactor#310 : SecurityConfiguration 리팩터
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
Labels: refactor

#313 Test#312: 테스트 실패 케이스 수정
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test

#318 Refactor#317 : Email 주소 유니크로 변경
  src/main/java/leaguehub/leaguehubbackend/entity/email/EmailAuth.java
Labels: refactor

#315 Feat#304 : 매치 채팅 내역 불러오기
  src/main/java/leaguehub/leaguehubbackend/controller/MatchChatController.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatService.java
Labels: feature

#325 test#314: 테스트용 db 배포 프로퍼티 수정
  src/main/resources/application-local.properties
  src/main/resources/application-test.properties
Labels: enhancement

#326 Refactor#321: 참가자 라이엇 api 최소화
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantSummonerDetail.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor

#324 Fix#320: 점수 업데이트 로직 수정 및 api 코드 수정
  src/main/java/leaguehub/leaguehubbackend/LeaguehubBackendApplication.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerInfo.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: bug, enhancement

#328 Refactor#322 : ParticipantDto에 channelId 추가
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ParticipantChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: feature

#331 Feat#319 : 익명 유저 요청 SecurityContext에 등록
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
Labels: feature

#334 Fix,Test#327: 버그 픽스 및 MatchPlayerService 테스트 코드 추가
  src/main/java/leaguehub/leaguehubbackend/config/MongoDataConfig.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/GameResult.java
  src/main/java/leaguehub/leaguehubbackend/mongo_repository/GameResultRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchPlayerServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceScoreTest.java
Labels: bug, enhancement

#336 Refactor#335 : MatchPlayerScoreInfoDto Refactor
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerInfo.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerScoreInfo.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchScoreInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/test/java/leaguehub/leaguehubbackend/fixture/MatchScoreListFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceScoreTest.java
Labels: test, refactor
