Repository TheUpperPart/leaguehub-backend, pull requests merged in 2023-06, with the labels that each got.

#8 Feat#7: Exception Feat
  src/main/java/leaguehub/leaguehubbackend/exception/auth/AuthExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/ExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/ExceptionResponse.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/GlobalErrorCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/MemberExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionCode.java
Labels: documentation, feature

#10 Feat#5 대회 생성 및 대회 게시판에 대한 CRUD
  lombok.config
  src/main/java/leaguehub/leaguehubbackend/controller/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/UpdateChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Category.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoard.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/MatchFormat.java
  src/main/java/leaguehub/leaguehubbackend/entity/constant/GlobalConstant.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/exception/ChannelBoardNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/exception/ChannelCreateException.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/exception/ChannelNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/exception/ResourceNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/MemberExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/exception/MemberNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelBoardRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelRuleRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchResultRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/member/MemberRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/main/java/leaguehub/leaguehubbackend/util/UserUtil.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelRuleTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
Labels: feature

#13 Feat#4 카카오 로그인 및 Access, Refresh 토큰 발급
  .gitignore
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/config/WebClientConfig.java
  src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
  src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoTokenRequestDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoTokenResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoUserDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/member/LoginMemberResponse.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/BaseRole.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/AuthExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/exception/AuthInvalidTokenException.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/GlobalExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/exception/GlobalServerErrorException.java
  src/main/java/leaguehub/leaguehubbackend/exception/kakao/KakaoExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/kakao/KakaoExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/kakao/exception/KakaoInvalidCodeException.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/exception/MemberNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/memberExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/repository/member/MemberRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/jwt/JwtService.java
  src/main/java/leaguehub/leaguehubbackend/service/kakao/KakaoService.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/main/resources/application.properties
Labels: feature

#17 Feat#9
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPoint.java
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/AuthExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/exception/AuthExpiredTokenException.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/exception/AuthInvalidTokenException.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/exception/AuthTokenNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/service/jwt/JwtService.java
Labels: feature

#16 Feat#15
  src/main/java/leaguehub/leaguehubbackend/controller/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/RequestCreateChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ResponseChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoard.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Role.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/exception/MemberNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/memberExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
Labels: bug, feature
