Repository TheUpperPart/leaguehub-backend, pull requests merged in 2023-08, with the labels that each got.

#96 Docs#50 참가자관련 Swagger UI API 작성
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantResponseDto.java
Labels: documentation, refactor

#100 Refactor#99: 요구사항 변경 및 엔티티 리팩터링
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoard.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchRank.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchResult.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/resources/application.properties
Labels: feature

#106 Feat#98: 채널 업데이트 기능 추가
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/UpdateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/exception/ChannelCreateException.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/exception/ChannelUpdateException.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
Labels: feature

#101 Feat#94 이메일인증 기능 구현
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/Controller/EmailController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/config/EmailConfig.java
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
  src/main/java/leaguehub/leaguehubbackend/dto/email/EmailDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/email/EmailAuth.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
  src/main/java/leaguehub/leaguehubbackend/exception/email/EmailExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/email/EmailExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/email/exception/DuplicateEmailException.java
  src/main/java/leaguehub/leaguehubbackend/exception/email/exception/InvalidEmailAddressException.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/MemberExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/MemberExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/repository/email/EmailAuthRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/member/MemberRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/email/EmailService.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/main/resources/static/invalidPage.html
  src/main/resources/static/verifiedPage.html
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: feature, refactor

#111 Feat#104 이메일 인증 관련 경기 참여 서비스 수정
  src/main/java/leaguehub/leaguehubbackend/exception/email/EmailExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/email/EmailExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/email/exception/UnauthorizedEmailException.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
Labels: feature

#115 Refactor#114
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ResponseChannelDto.java
Labels: feature, refactor

#119 Refactor#117: 채널 업데이트 API 분리
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelRuleController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelRuleDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/UpdateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
Labels: refactor

#120 Test#102 : Email Controller, Service 테스트 구현
  src/main/java/leaguehub/leaguehubbackend/Controller/EmailController.java
  src/main/java/leaguehub/leaguehubbackend/entity/email/EmailAuth.java
  src/main/java/leaguehub/leaguehubbackend/service/email/EmailService.java
  src/test/java/leaguehub/leaguehubbackend/controller/EmailControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/email/EmailServiceTest.java
Labels: test

#122 Test#108: #98, #107 테스트 코드 작성 및 버그 픽스
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelRuleDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MatchControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelRuleControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelRuleTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchRankTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchResultTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchRankServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: bug, test

#126 doc : Swagger UI 어노테이션 추가
  src/main/java/leaguehub/leaguehubbackend/Controller/EmailController.java
Labels: documentation

#129 Feat#128 사용자 채널 참가 구현
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/ParticipantNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: feature, refactor

#130 Feat#127 사용자 프로필과 마이페이지 API를 분리
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/dto/member/MypageResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/member/ProfileDto.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
Labels: feature, refactor

#134 Test#132 : Member 프로필 조회, 로그인 관련 테스트 변경
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/MypageResponseFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ProfileFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: test, refactor

#133 Test#131: #128, 이메일 인증관련 테스트코드 작성
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test

#136 Feat#68: 개인별 커스텀 채널 인덱스 기능 구현
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ParticipantChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: feature

#140 Fix: ChannelService 누락 코드 추가
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
Labels: bug

#142 Fix#141: 핫픽스 수정
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
Labels: bug

#144 Refactor : UserUtil 멤버 권한 변경
  src/main/java/leaguehub/leaguehubbackend/util/UserUtil.java
Labels: refactor

#145 Docs#124 Controller Swagger 작성
  src/main/java/leaguehub/leaguehubbackend/Controller/EmailController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelRuleController.java
  src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardLoadDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelRuleDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ParticipantChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/UpdateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/email/EmailDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantResponseDto.java
Labels: documentation

#147 Refactor#109: 공통 메서드 추출
  src/main/java/leaguehub/leaguehubbackend/Controller/EmailController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
  src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoTokenResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoUserDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ResponseUserGameInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/email/EmailAuth.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/AuthExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/exception/ChannelRequestException.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/GlobalErrorCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/kakao/KakaoExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/MemberExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/repository/email/EmailAuthRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/email/EmailService.java
  src/main/java/leaguehub/leaguehubbackend/service/jwt/JwtService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchRankService.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/main/java/leaguehub/leaguehubbackend/util/UserUtil.java
  src/test/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPointTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/EmailControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/JwtControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelRuleControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/MatchFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ParticipantFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ProfileResponseFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/email/EmailServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/kakao/KakaoServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor

#151 Feat#116: Dto Valid 추가
  src/main/java/leaguehub/leaguehubbackend/Controller/EmailController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardLoadDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelRuleDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/email/EmailDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/GameRankDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ResponseStatusPlayerDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ResponseUserGameInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/GlobalExceptionHandler.java
Labels: feature

#156 Config#155: Cors 및 MySql 설정
  src/main/java/leaguehub/leaguehubbackend/config/WebConfig.java
  src/main/resources/application.properties
Labels: feature

#154 Feat#150: 채널 관련 email 인증및 Enum 리팩터링
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Category.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/MatchFormat.java
  src/main/java/leaguehub/leaguehubbackend/entity/constant/GlobalConstant.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/BaseRole.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/GameTier.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/RequestStatus.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Role.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: feature, refactor

#153 Refactor#148: 중복 메서드 삭제
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
Labels: refactor

#152 feat#137: customIndex 정렬 기능 추가
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelBoardRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
Labels: feature

#164 Fix: 이메일 체크하는 메서드 위치 이동
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
Labels: bug

#161 Fix#135 : 동일한 시간 때 접속시 동일 refreshToken 생성 수정
  src/main/java/leaguehub/leaguehubbackend/service/jwt/JwtService.java
Labels: bug

#160 Fix#138 : JwtFilter 토큰과 관련 없는 에러 수정
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPoint.java
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/AuthExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/util/UserUtil.java
Labels: bug

#165 Refactor: @EmailDto 추가 및 채널 생성시 Dto 값 변경
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ResponseCreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/email/EmailDto.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: refactor

#169 fix#167: cors 설정 버그 픽스
  src/main/java/leaguehub/leaguehubbackend/config/CorsConfig.java
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
  src/main/java/leaguehub/leaguehubbackend/config/WebConfig.java
Labels: bug

#168 test#166: Dto 값 변경에 따른 테스트 코드 변경
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelRuleControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
Labels: test

#171 Test: Dto 값 변경에 따른 참가자 관련 테스트 코드 변경
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ParticipantFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test

#175 Test#174 : 코드 변경으로 인한 테스트코드 변경
  src/test/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPointTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/EmailControllerTest.java
Labels: test

#176 Refactor#172: 클래스, 필드명 변경
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ParticipantChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ResponseChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/UpdateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/GameCategory.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor

#173 Feat#158 : 닉네임 수정 기능 구현
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/dto/member/NicknameRequestDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: feature, test

#178 fix: #172로 인한 버그 발생
  src/main/java/leaguehub/leaguehubbackend/controller/EmailController.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/controller/channel/ChannelRuleController.java
Labels: bug

#180 Feat#48: 경기 참가자 랜덤 배정 처리
  src/main/java/leaguehub/leaguehubbackend/Controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/exception/MatchNotEnoughPlayerException.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MatchControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchRankTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchResultTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchRankServiceTest.java
Labels: feature

#184 Refactor#183: 티어 반환 엔티티 및 서비스 수정
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelRuleDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/GameRankDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ResponseUserGameInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/GameTier.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MatchControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelRuleControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelRuleTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchRankTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchResultTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchRankServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor

#191 docs#189: Restful API 재작성
  src/main/java/leaguehub/leaguehubbackend/controller/EmailController.java
  src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
  src/main/java/leaguehub/leaguehubbackend/controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardController.java
Labels: documentation

#193 Refactor#192: #189 수정에 따른 컨트롤러 및 테스트 코드 수정
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantDto.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/EmailControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/JwtControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ParticipantFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor

#196 Refactor#190: 경기 배정 및 매치 엔티티 수정
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchRoundListDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceTest.java
Labels: refactor

#198 Test#146: 채널 커스텀 정렬, 분리된 채널보드 가져오기 API 테스트 추가
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test

#197 Feat#186: 참가자 첫 배정 및 대진표 조회 서비스 구현
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerInfo.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceTest.java
Labels: feature

#201 Feat#179: 엔티티 관계 정리 및 그에 따른 코드 리팩터
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoard.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchRank.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchResult.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelRuleTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: feature, refactor

#206 Feat#203 : 소켓 기본설정, 시큐리티 설정 구현
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
  src/main/java/leaguehub/leaguehubbackend/config/StompErrorHandler.java
  src/main/java/leaguehub/leaguehubbackend/config/StompHandler.java
  src/main/java/leaguehub/leaguehubbackend/config/WebSocketConfig.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/service/jwt/JwtService.java
  src/main/resources/application.properties
Labels: feature

#205 Refactor: 참가자 권한 목록 수정
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Role.java
Labels: refactor

#211 Refactor#209: JPA 성능 튜닝을 위한 리팩터링
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelBoardRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelRuleRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelRuleService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: refactor

#216 feat#105: 채널의 상태 업데이트 API 구현
  src/main/java/leaguehub/leaguehubbackend/controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelStatus.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
Labels: feature

#221 Feat#185: 경기가 끝난 후 다음 매치 재배정
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/ParticipantStatus.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#220 refactor: 매치 생성 및 조회 시 설정되는 값 변경
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: refactor

#227 Refactor#225: 엔티티 삭제 및 로직 변경에 따른 수정
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchRankResultDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchRank.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchResult.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRankRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchResultRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchResultService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MatchControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchRankTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/match/MatchResultTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/MatchFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchRankServiceTest.java
Labels: enhancement, invalid, feature, refactor

#230 feat#229: MatchSet 구현
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchSet.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchSetRepository.java
Labels: enhancement

#234 Feat#218,#224: 경기 종료후 점수 업데이트 및 매치 종료 기능 구현
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchPlayerInfo.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/RiotAPIDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchSet.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchSetRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: enhancement

#235 Feat#233: Match 관련 Exception 처리 및 GlobalException 추가
  src/main/java/leaguehub/leaguehubbackend/exception/global/GlobalExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/MatchExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/match/exception/MatchAlreadyUpdateException.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MatchControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/MatchFixture.java
Labels: enhancement
