Repository TheUpperPart/leaguehub-backend, pull requests merged in 2023-10, with the labels that each got.

#337 Feat#330: 매치 알람 기능 추가
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: enhancement

#340 Fix#339 : channelId 추가
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
Labels: bug

#347 Refactor#346: MongoDB 삭제 및 리팩터링
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/LeaguehubBackendApplication.java
  src/main/java/leaguehub/leaguehubbackend/config/MongoDataConfig.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/GameResultDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchRankResultDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/GameResult.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchRank.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchSet.java
  src/main/java/leaguehub/leaguehubbackend/mongo_repository/GameResultRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchRankRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchSetRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/resources/application-local.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchPlayerServiceTest.java
Labels: enhancement

#342 Fix#329: 채널 생성시 NullPointException 에러 수정
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
Labels: bug

#348 Feat#343 : 매치 채팅 내역 조회 구현
  src/main/java/leaguehub/leaguehubbackend/controller/MatchChatController.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchScoreInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatService.java
Labels: feature

#349 Feat#344: 현재 참여중인 플레이어면 진행중인 라운드 표시
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MyMatchDto.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
Labels: enhancement

#351 Feat#350 : Match 정보 조회 정보 변경
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchScoreInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#353 Refactor#352 : channelId, channelLink로 변경
  src/main/java/leaguehub/leaguehubbackend/controller/MatchChatController.java
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/chat/MatchMessage.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatService.java
Labels: refactor

#355 Fix#354: PathVariable 주소 수정
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
Labels: bug

#357 Fix#356 : 관리자페이지 채팅 조회 반환값 수정
  src/main/java/leaguehub/leaguehubbackend/controller/MatchChatController.java
Labels: bug

#359 Fix#358: 매치 배정 때 비교하는 변수 수정
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: bug

#361 fix#360: 생성시 matchCurrentSet 값 변경
  src/main/java/leaguehub/leaguehubbackend/entity/match/Match.java
Labels: bug

#363 Feat#357 : 매치정보 조회시 Host일 때 -1L 반환
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: feature

#366 Feat#345: 관리자 페이지에서 현재 진행중인 매치 리스트를 보여주는 기능
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: enhancement

#369 Refactor#365: 라운드 배정 시 matchStatus 상태 변경 추가
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: refactor

#374 Feat#371 : 관리자 호출시 관리자 호출 메시지 저장
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/chat/MatchMessage.java
  src/main/java/leaguehub/leaguehubbackend/entity/chat/MessageType.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatService.java
Labels: feature

#375 Feat#373: 체크인, 점수 업데이트시 유효성 매치 종료 검사 추가
  src/main/java/leaguehub/leaguehubbackend/repository/match/MatchPlayerRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
Labels: enhancement

#376 Feat#372: 강퇴, 실격 기능 추가
  src/main/java/leaguehub/leaguehubbackend/entity/match/PlayerStatus.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: bug, feature

#380 Refactor#379: 관리자 호출시 반환값 설정
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchCallAdminDto.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: refactor

#386 fix#384: convertMatchPlayerDto 등수 추가
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: bug

#389 fix: convertMatchPlayerDto 중복 등수 추가 및 통합
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: bug, duplicate, refactor

#382 Refactor : jwt, stomp 패키지 구조 변경
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
  src/main/java/leaguehub/leaguehubbackend/config/WebSocketConfig.java
  src/main/java/leaguehub/leaguehubbackend/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/leaguehub/leaguehubbackend/config/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/config/stomp/StompErrorHandler.java
  src/main/java/leaguehub/leaguehubbackend/config/stomp/StompHandler.java
  src/test/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPointTest.java
  src/test/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilterTest.java
Labels: refactor

#395 fix#394: Json Parsing이 안되는 버그 수정
  src/main/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardIndexListDto.java
Labels: bug

#392 Test : 매치 조회 테스트 수정
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceScoreTest.java
Labels: test

#397 Fix#396: 채널 보드 인덱스가 업데이트 되지 않은 문제 해결
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardIndexListDto.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
Labels: bug

#399 fix: 관리자 부여 시 이메일 인증 검증 추가
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: bug

#402 Feat#383: 채팅시 관리자 이름 저장
  src/main/java/leaguehub/leaguehubbackend/dto/chat/MatchMessage.java
  src/main/java/leaguehub/leaguehubbackend/entity/chat/MessageType.java
  src/main/java/leaguehub/leaguehubbackend/service/chat/MatchChatService.java
Labels: feature

#401 Feat#400: 기권처리 실격처리 웹소켓 전환
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantIdDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantIdResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/match/PlayerStatus.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: feature
