Repository TheUpperPart/leaguehub-backend, pull requests merged in 2023-12, with the labels that each got.

#431 Feat#430: 현재 라운드를 저장할 변수 추가 및 기능 수정
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: enhancement, feature

#447 Config#440: 도커 파일 생성 및 prod 프로파일 변경
  Dockerfile
  src/main/java/leaguehub/leaguehubbackend/entity/BaseTimeEntity.java
  src/main/java/leaguehub/leaguehubbackend/exception/global/GlobalExceptionHandler.java
  src/main/resources/application-prod.properties
Labels: enhancement

#449 docs: 해당 서비스의 README 작성
  README.md
Labels: documentation
