Repository TheUpperPart/leaguehub-backend, pull requests merged in 2023-07, with the labels that each got.

#25 Refactor#23 티어 조회에 대한 리팩터링
  src/main/java/leaguehub/leaguehubbackend/entity/participant/GameTier.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: feature

#26 Test#22
  src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
  src/main/java/leaguehub/leaguehubbackend/exception/auth/AuthExceptionHandler.java
  src/test/java/leaguehub/leaguehubbackend/controller/JwtControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/jwt/JwtServiceTest.java
Labels: test

#28 Test#27
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoUserDto.java
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/KakaoTokenResponseDtoFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/KakaoUserDtoFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/kakao/KakaoServiceTest.java
Labels: test

#29 Feat#20
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/dto/member/ProfileResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/main/java/leaguehub/leaguehubbackend/util/SecurityUtils.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ProfileResponseFixture.java
Labels: feature

#33 Feat#24 : 채널 참가자에 대한 정보 저장 및 조회 개발
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/GameRankDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/RequestPlayerDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ResponseUserDetailDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelRule.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/GameTier.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/ParticipantGameIdNotFoundException.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/ParticipantInvalidLoginException.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/ParticipantInvalidPlayCountException.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/ParticipantInvalidRankException.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/ParticipantInvalidRoleException.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelRuleRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelRuleTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/MatchFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchRankServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: feature

#34 Feat#18: 게시판 CRUD API 구현
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/RequestChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ResponseBoardDetail.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/InvalidParticipantAuthException.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
Labels: feature

#37 Feat#36 : default 유저 추가
  src/main/java/leaguehub/leaguehubbackend/LeaguehubBackendApplication.java
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/LoginProvider.java
  src/main/java/leaguehub/leaguehubbackend/util/UserUtil.java
Labels: feature

#38 Feat#35 로그아웃 기능
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: feature

#45 Test#19
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/exception/channel/ChannelExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/LeaguehubBackendApplicationTests.java
  src/test/java/leaguehub/leaguehubbackend/controller/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/JwtControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/jwt/JwtServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/kakao/KakaoServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: bug, feature, test

#47 Test#42
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/CreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/GameTier.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelRuleRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ParticipantFixture.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test

#49 Feat#46 Swagger 문서화 환경 구축
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/config/SecurityConfiguration.java
  src/main/java/leaguehub/leaguehubbackend/config/SwaggerConfig.java
  src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
Labels: feature

#57 fix: AuthExceptionHandler 누락
  src/main/java/leaguehub/leaguehubbackend/exception/auth/AuthExceptionHandler.java
Labels: bug

#54 Refactor#53 대회참가자 관련 리팩터링
  src/main/java/leaguehub/leaguehubbackend/Controller/participant/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/RequestStatus.java
  src/test/java/leaguehub/leaguehubbackend/entity/participant/ParticipantTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test, refactor

#59 Feat#58 최초 로그인시 Guest와 일반 User 구분
  src/main/java/leaguehub/leaguehubbackend/Controller/MemberController.java
  src/main/java/leaguehub/leaguehubbackend/controller/KakaoController.java
  src/main/java/leaguehub/leaguehubbackend/dto/member/LoginMemberResponse.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/BaseRole.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/MemberExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/MemberExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/exception/DuplicateEmailException.java
  src/main/java/leaguehub/leaguehubbackend/exception/member/exception/InvalidEmailAddressException.java
  src/main/java/leaguehub/leaguehubbackend/repository/member/MemberRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: feature, test

#60 Test#44: 채널 보드 컨트롤러 테스트
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/ChannelFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
Labels: bug, test, refactor

#62 fix: ParticipantController 중복 삭제
  src/main/java/leaguehub/leaguehubbackend/Controller/participant/ParticipantController.java
Labels: bug

#71 Feat#64: loadChannels API 작성, createChannel 반환 값 추가
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ParticipantChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ResponseCreateChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
Labels: feature

#72 Test#70: loadChannels, findParticipateList 테스트 추가
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelServiceTest.java
Labels: test

#80 Feat#65: 채널 보드 인덱스 기능 구현
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/Controller/channel/ChannelBoardController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelBoardLoadDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ResponseChannelDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/UpdateChannelBoardDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoard.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelBoardRepository.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/entity/channel/ChannelBoardTest.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
Labels: feature, refactor

#84 Fix#83 : 로그아웃시 SecurityContext 초기화
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: feature, test

#82 Test#67 : Jwt 필터 테스트 코드 작성
  src/test/java/leaguehub/leaguehubbackend/config/JwtAuthenticationEntryPointTest.java
  src/test/java/leaguehub/leaguehubbackend/config/JwtAuthenticationProcessingFilterTest.java
Labels: test

#87 Feat#79 관리자 권한 부여, 대회 참여자 강퇴 구현
  src/main/java/leaguehub/leaguehubbackend/Controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/PlayerDto.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ResponseStatusPlayerDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/repository/particiapnt/ParticipantRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: feature, refactor

#88 Test#86 Participant 서비스, 컨트롤러 테스트 코드 작성
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test

#91 Feat#89 클라이언트 UserProfile 요청시 email 정보 추가
  src/main/java/leaguehub/leaguehubbackend/dto/member/ProfileResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
  src/main/java/leaguehub/leaguehubbackend/service/member/MemberService.java
Labels: feature

#92 Feat#90 채널 룰과 참가자 제한 관리 작업
  src/main/java/leaguehub/leaguehubbackend/Controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantResponseDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/Channel.java
  src/main/java/leaguehub/leaguehubbackend/entity/participant/Participant.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/ParticipantExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/participant/exception/ParticipantRealPlayerIsMaxException.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: feature, refactor

#95 Test#93 feat#90에 대한 테스트 코드 작성
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: test, refactor
