Repository TheUpperPart/leaguehub-backend, pull requests merged in 2023-11, with the labels that each got.

#408 Fix#407: Json Key 첨부를 위한 Dto 추가
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/dto/match/MatchSetCountDto.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: bug

#410 refactor#409: post의 @RequestBody를 Get 반환 값 Dto로 통일
  src/main/java/leaguehub/leaguehubbackend/controller/MatchController.java
Labels: refactor

#411 feat: 실격, 기권 시 점수 -1 업데이트 기능 구현
  src/main/java/leaguehub/leaguehubbackend/entity/match/MatchPlayer.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: feature

#414 Feat#413: TFT 공지사항 스크래핑을 구현
  build.gradle
  src/main/java/leaguehub/leaguehubbackend/config/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/leaguehub/leaguehubbackend/controller/NoticeController.java
  src/main/java/leaguehub/leaguehubbackend/dto/notice/TftNotice.java
  src/main/java/leaguehub/leaguehubbackend/service/notice/NoticeService.java
Labels: feature

#412 feat: 이미지 업로드 시 파일 크기 제한 설정 추가
  src/main/resources/application-local.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
Labels: feature

#420 Feat#417: 해당 채널에 대한 정보 테이블 추가
  src/main/java/leaguehub/leaguehubbackend/controller/channel/ChannelInfoController.java
  src/main/java/leaguehub/leaguehubbackend/dto/channel/ChannelInfoDto.java
  src/main/java/leaguehub/leaguehubbackend/entity/channel/ChannelInfo.java
  src/main/java/leaguehub/leaguehubbackend/repository/channel/ChannelInfoRepository.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelInfoService.java
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelService.java
Labels: enhancement, feature

#422 Feat#421: 게임사 닉네임, 전적검색 요청 수정에 따른 기능 변경
  src/main/java/leaguehub/leaguehubbackend/dto/participant/ParticipantDto.java
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/service/participant/ParticipantService.java
Labels: feature

#426 fix425: 중복되지 않은 이메일 미전송 버그 수정
  src/main/java/leaguehub/leaguehubbackend/service/email/EmailService.java
Labels: bug

#429 fix#428: 채널 경기 배정시 이미 진행중인 매치 체크
  src/main/java/leaguehub/leaguehubbackend/service/match/MatchService.java
Labels: bug

#437 Test#436: Board, Email 테스트 수정
  src/main/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardService.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/fixture/UserFixture.java
  src/test/java/leaguehub/leaguehubbackend/service/channel/ChannelBoardServiceTest.java
Labels: bug

#438 Feat#433: FC online, 롤, 하스스톤 공지 스크래핑 구현
  src/main/java/leaguehub/leaguehubbackend/exception/notice/NoticeExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/exception/notice/NoticeExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/exception/notice/exception/NoticeUnsupportedException.java
  src/main/java/leaguehub/leaguehubbackend/exception/notice/exception/WebScrapingException.java
  src/main/java/leaguehub/leaguehubbackend/service/notice/NoticeService.java
Labels: feature
