Repository TheUpperPart/leaguehub-backend, pull requests merged in 2024-03, with the labels that each got.

#467 Docs#466 : 깨진 이미지 링크 수정
  README.md
Labels: documentation

#465 Refactor#464 : 안전한 토큰 저장을 위한 HttpOnly와 Secure 쿠키 설정
  src/main/java/leaguehub/leaguehubbackend/domain/member/controller/KakaoController.java
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
Labels: enhancement, refactor

#468 Refactor#458 : Participant 패키지 구조 개선
  src/main/java/leaguehub/leaguehubbackend/domain/channel/controller/ChannelController.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/controller/ParticipantController.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/controller/ParticipantManagementController.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/controller/ParticipantQueryController.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/controller/ParticipantRoleAndPermissionController.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/service/ParticipantManagementService.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/service/ParticipantQueryService.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/service/ParticipantRoleAndPermissionService.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/service/ParticipantService.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/service/ParticipantWebClientService.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor
