Repository TheUpperPart/leaguehub-backend, pull requests merged in 2024-04, with the labels that each got.

#472 Feat#469 : 공지사항 Notice 테이블 생성 및 수동 업데이트 서비스 구현
  src/main/java/leaguehub/leaguehubbackend/domain/notice/controller/NoticeController.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/dto/NoticeDto.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/entity/GameType.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/entity/Notice.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/exception/NoticeExceptionCode.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/exception/NoticeExceptionHandler.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/exception/exception/NoticeUnsupportedException.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/exception/exception/WebScrapingException.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/repository/NoticeRepository.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/service/NoticeService.java
  src/main/java/leaguehub/leaguehubbackend/global/notice/NoticeService.java
  src/main/java/leaguehub/leaguehubbackend/global/notice/controller/NoticeController.java
Labels: feature

#471 Refactor#470 : Member 패키지 구조 개선
  src/main/java/leaguehub/leaguehubbackend/domain/match/service/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/controller/JwtController.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberAuthController.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberInfoController.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/service/KakaoService.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/service/MemberAuthService.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/service/MemberProfileService.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/service/MemberService.java
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/kakao/KakaoServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/member/MemberServiceTest.java
Labels: refactor

#477 Test#476 : 공지사항 테스트 코드 작성
  src/test/java/leaguehub/leaguehubbackend/controller/NoticeControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/notice/NoticeServiceTest.java
Labels: test

#475 Refactor#473 : Match 패키지 구조 개선
  src/main/java/leaguehub/leaguehubbackend/domain/channel/service/ChannelBoardService.java
  src/main/java/leaguehub/leaguehubbackend/domain/match/controller/MatchController.java
  src/main/java/leaguehub/leaguehubbackend/domain/match/controller/MatchPlayerController.java
  src/main/java/leaguehub/leaguehubbackend/domain/match/controller/MatchQueryController.java
  src/main/java/leaguehub/leaguehubbackend/domain/match/service/MatchPlayerService.java
  src/main/java/leaguehub/leaguehubbackend/domain/match/service/MatchQueryService.java
  src/main/java/leaguehub/leaguehubbackend/domain/match/service/MatchService.java
  src/main/java/leaguehub/leaguehubbackend/domain/match/service/MatchWebClientService.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchPlayerServiceTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceScoreTest.java
  src/test/java/leaguehub/leaguehubbackend/service/match/MatchServiceTest.java
Labels: refactor

#479 Refactor#478 : Query 서비스부분 readOnly를 통한 메모리 절약
  src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberInfoController.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/service/MemberProfileService.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/service/ParticipantQueryService.java
Labels: refactor

#481 Test#480 : 테스트 코드 오류 수정
  src/test/java/leaguehub/leaguehubbackend/controller/KakaoControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/MemberControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/ParticipantControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/controller/channel/ChannelBoardControllerTest.java
  src/test/java/leaguehub/leaguehubbackend/service/participant/ParticipantServiceTest.java
Labels: refactor

#483 Config#482 : CD Workflow 설정 및 Docker 관련 작업 자동화
  .github/workflows/gradle.yml
Labels: enhancement

#487 Refactor#463: 토큰 추출 방식 헤더에서 쿠키로 변경
  src/main/java/leaguehub/leaguehubbackend/domain/member/constant/TokenConstant.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberAuthController.java
  src/main/java/leaguehub/leaguehubbackend/domain/member/service/JwtService.java
  src/main/java/leaguehub/leaguehubbackend/domain/participant/exception/ParticipantExceptionCode.java
  src/main/resources/application-prod.properties
Labels: enhancement

#489 Fix#488: 공지사항 요청시 Enum 반환 타입 변환 오류 수정
  src/main/java/leaguehub/leaguehubbackend/domain/notice/controller/NoticeController.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/entity/GameType.java
  src/main/java/leaguehub/leaguehubbackend/domain/notice/service/NoticeService.java
  src/test/java/leaguehub/leaguehubbackend/service/notice/NoticeServiceTest.java
Labels: bug
